### ISSUE TITLE
Power off logo adapt to screen mode

### ISSUE THREAD

**Issue by neilswann80** [orontee/taranis#101]
# Context

Original comment by @neilswann80 :

> Currently the shutdown logo is always created in "light mode".  Could this be changed to reflect the dark-mode status?

# Analysis

If I understand well, taking screen mode into account is a mater of listening to `EVT_SCREEN_INVERSION_MODE_CHANGED` and call `IvGetScreenModeInversion()` when rendering the logo.

**Comment by orontee** [comment]
![taranis_weather_forecast](https://github.com/user-attachments/assets/daf68554-c43d-4dbc-88f1-890d9e80814c)
![taranis_weather_forecast_dark](https://github.com/user-attachments/assets/b7d69725-a663-4d78-ab02-c441ade5fa8b)

**Comment by orontee** [comment]
See #102 for the second request
