### ISSUE TITLE
Remove power off logo when generation is disabled

### ISSUE THREAD

**Issue by orontee** [orontee/taranis#102]
# Context

Original comment by @neilswann80 :

> Would it also be worth removing the Taranis shutdown logo if disabling the feature?  Otherwise a potentially old weather image will occasionally show if the user selects the random logo setting.

# Analysis

**Comment by orontee** [comment]
At first sight, when file is removed but device setting is still equal to `taranis_weather_forecast.bmp`, the setting is automatically updated to "Book cover".

**Comment by neilswann80** [comment]
Thanks for all the recent changes/fixes.  They all work great on my device.

**Comment by orontee** [comment]
Good to know, I don't test much for such small changes. I'll now try to spend some time on my other PB project, a port of Gargoyle...
