### ISSUE TITLE
Configuration editor

### ISSUE THREAD

**Issue by orontee** [orontee/taranis#2]
https://github.com/Programmist11180/pbxmms2client/blob/master/src/settings.cpp
http://komary.net/pbimageviewer/

**Comment by orontee** [comment]
Failed to make configuration editor to work. Crash...

Will do #17 .

**Comment by orontee** [comment]
![sreenshot](https://github.com/orontee/taranis/assets/2065954/0075cf5a-3759-4793-8eef-cc3b811eaaf1)

**Comment by neilswann80** [comment]
Parameters option works very well.  I like it!
