### ISSUE TITLE
Touch control to swipe between pages

### ISSUE THREAD

**Issue by orontee** [orontee/taranis#27]
https://github.com/pocketbook/SDK_6.3.0/blob/6.5/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot/usr/local/include/scrollview.h#L2

Source: https://www.mobileread.com/forums/showpost.php?p=4354379&postcount=4

**Comment by orontee** [comment]
@neilswann80 I'd be happy to have your feedback on this feature.

It's available from this pre-release: https://github.com/orontee/taranis/releases/tag/v1.2.0-rc1.

**Comment by neilswann80** [comment]
Nicely done.  Was it difficult to implement?

What I did notice is that long swipes work 100% of the time, but smaller swipes (if holding one-handed for instance) weren't always acknowledged.  Can the swipe distance to activate the page turn be reduced a little?

**Comment by orontee** [comment]
> Nicely done. Was it difficult to implement?

Not really, around 100 lines. See: https://github.com/orontee/taranis/blob/main/src/swipe.h#L19.

> What I did notice is that long swipes work 100% of the time, but smaller swipes (if holding one-handed for instance) weren't always acknowledged. Can the swipe distance to activate the page turn be reduced a little?

What do you mean by "long"? Long duration or long distance? There are threshold for both in the code. I guess we'll have to find better values than the arbitrary I've chosen.

Don't know whether it works well with large screens...

> There's quite a large gap in the 8-day view now, between windspeed and rainfall. Looks to be an empty column. Is there a new feature appearing there?

Yep, see #42.

**Comment by neilswann80** [comment]
> What do you mean by "long"? Long duration or long distance? There are threshold for both in the code. I guess we'll have to find better values than the arbitrary I've chosen.

Long distance.  

I'd guess it would be better to set a specific pixel distance rather than a percentage of  ScreenWidth().  I'd think swipe distance is likely more uniform than the sizes of device screen.  :)

**Comment by orontee** [comment]
> > What do you mean by "long"? Long duration or long distance? There are threshold for both in the code. I guess we'll have to find better values than the arbitrary I've chosen.
> 
> Long distance.
> 
> I'd guess it would be better to set a specific pixel distance rather than a percentage of ScreenWidth(). I'd think swipe distance is likely more uniform than the sizes of device screen. :)

Yes. But right now distance is expressed in pixels, resolution should enters the equation.

**Comment by neilswann80** [comment]
Ah yes, PPI between old and new devices could be quite different.

**Comment by orontee** [comment]
Hum alignment of columns is wrong (not surprising but so ugly)...

**Comment by orontee** [comment]
Unfortunately since we're using a variable pitch font it's not that simple!

**Comment by orontee** [comment]
>  Is if feasible to add the day/number of the month in the blue box?

Yeah, could be done.

Thinking of red box again, did you change units? Depending on the unit system, this space could be narrower. May be moon phase is not that important; I'll try to work on a better layout first. 

I am also thinking of wind direction in place of humidity. But it's another topic.
