### ISSUE TITLE
Provide screenshot of the daily forecast to be used as power off logo

### ISSUE THREAD

**Issue by orontee** [orontee/taranis#28]
Source: https://www.mobileread.com/forums/showpost.php?p=4354379&postcount=4

From the official documentation:
![image](https://github.com/orontee/taranis/assets/2065954/d89c5e3d-bd8f-478a-af54-00f89e5c60f5)

Unfortunately no idea of how to set that "boot logo"...

**Comment by neilswann80** [comment]
Also noticed a couple of references within inkview.h:

PageSnapshot();
#define REQ_SCREENSHOT

The latter I'm assuming would be called with something like:

iv_ipc_request( REQ_SCREENSHOT, 1, NULL, 0, 0);


Can't find any further info on their use.  I've tried compiling a simple inkview app that calls these functions, but no screenshots appear in /mnt/ext1/screens
or any tmp directory I've searched.

**Comment by neilswann80** [comment]
FYI... one of the above commands definitely changed the bootlogo, just noticed after a reboot.

**Comment by orontee** [comment]
> FYI... one of the above commands definitely changed the bootlogo, just noticed after a reboot.

How the new bootlogo looks like? Is it a taranis snapshot??

**Comment by neilswann80** [comment]
I added the command to a Tetris app I'm playing with, so the bootlogo was a screenshot of that.  I'll see if I can find the location it's saved to.

**Comment by neilswann80** [comment]
It's definitely the command: PageSnapshot();

I have a custom bootlogo set and it's overriding that, I have to manually set it back to my custom one or it will continue to show the PageSnapshot with every reboot; so that's good! :)

If I can find the save location, I'm hoping deleting the bitmap will restore my custom bootlogo for next reboot. 

If the PageSnapshot can be moved to /mnt/ext1/system/logo/offlogo, then we should be able to set it to active within /mnt/ext/system/config/global.cfg

**Comment by orontee** [comment]
> (...) If the PageSnapshot can be moved to /mnt/ext1/system/logo/offlogo, then we should be able to set it to active within /mnt/ext/system/config/global.cfg

I am not sure I follow you. Why not simply call `ibitmap *BitmapFromScreen(int x, int y, int w, int h);` and save to /mnt/ext1/system/logo/offlogo?

**Comment by neilswann80** [comment]
Ah, yeah, I missed that command.  What is the syntax for saving after the BitmapFromScreen function is called?

**Comment by neilswann80** [comment]
Figured it out.  Need to combine the functions:

int SaveBitmap(const char *filename, const ibitmap *bm);
ibitmap *BitmapFromScreen(int x, int y, int w, int h);

So this:

SaveBitmap("/mnt/ext1/Photo/test.bmp", BitmapFromScreen(0, 0, 1072, 1448));

Worked for me on my HD3 with resolution of 1072x1448.

**Comment by orontee** [comment]
`inkview.h` defines `USEROFFLOGOPATH`. After saving a BMP to, say `USEROFFLOGOPATH + "/taranis_weather_forecast.bmp", a new item `taranis_weather_forecast.bmp` is available in "Parameters / Appearance / Power off logo"; Selecting that item uses the BMP as power off logo...

Plan:
* See if it's possible to render on a virtual screen to save a bitmap with forecasts but not current weather data, nor menu button
* If not possible, call `BitmapFromScreen(0, 0, ScreenWidth(), ScreenHeight()));` and clear menu button area at least
* Save bitmap each time the data is refreshed
* No need to check user config since we're saving bitmaps to custom files.

**Comment by neilswann80** [comment]
Nice!  😄 

This leaves it up to the user whether to select that specific wallpaper via a manual change of settings.

Although this would mean that if selecting the "Random" power off logo option it would appear too, mixed in with the user selected images.  Perhaps an on/off setting for adding/removing the `taranis_weather_forecast.bmp` from `USEROFFLOGOPATH` is still needed?

**Comment by neilswann80** [comment]
> But first of all one must succeed in rendering a dedicated image since current weather and menu button don't make sense in a poweroff image!

What do you mean by "current weather" in this context?  

Could you create a variable state that controls button transparency that's enabled for the screenshot process?

**Comment by orontee** [comment]
> What do you mean by "current weather" in this context?

From left to right, top to bottom of Taranis screen there's: A "location box", the menu button, then what I call the "current weather box". The displayed information is valid for the current time. So it doesn't make sense to have it on a poweroff image.

Maybe it's not a real problem since the refresh timestamp is displayed...

> Could you create a variable state that controls button transparency that's enabled for the screenshot process?

Could be possible but if it is it's not easier than removing that button temporarily. The true problem is to render the image "off screen" but I am pretty confident that it works if a sub-task is started. I'll work on this next week.

**Comment by orontee** [comment]
Just read from the "documentation" of `SetCanvas`:

> One can manually create canvas, pass it to SetCanvas() and then draw into it using such
functions as DrawPixel() and FillArea().

Thus generating the image to use as wallpaper shouldn't be difficult.

**Comment by orontee** [comment]
![offlogo](https://github.com/orontee/taranis/assets/2065954/110b0691-4f64-4c00-9030-5ca7c19766dc)
