### ISSUE TITLE
Pressing/clicking on city/location, but cancelling out, should not refresh data

### ISSUE THREAD

**Issue by neilswann80** [orontee/taranis#39]
It's easy to click/press the location by mistake, choosing to exit without making changes triggers a full refresh/resync.

**Comment by orontee** [comment]
@neilswann80 This is available in https://github.com/orontee/taranis/releases/tag/v1.1.0-rc4

**Comment by neilswann80** [comment]
That was fast!  I'll test right away.

**Comment by orontee** [comment]
Yes but I made many changes to fix #38 in the same pre-release. Dangerous but there was useless data request and screen refresh!

**Comment by neilswann80** [comment]
Feels much smoother now, much nicer to move page to page.  Nicely done!

**Comment by orontee** [comment]
Good news! I'll release this as is, Sunday will be dedicated to reading and cycling on my side!

Thanks for your feedbacks.

**Comment by neilswann80** [comment]
Enjoy the reading and cycling!  I'm likely off for a hike.  As for reading, just started "Billy Summers" by Stephen King.  Gripped so far.  I find his work a bit hit and miss, but this seems to be in the hit category.
