### ISSUE TITLE
Ensure favourite locations won't disappear from history

### ISSUE THREAD

**Issue by neilswann80** [orontee/taranis#40]
Add "add favourite location" menu button

Have a separate json file for specifically user selected locations, similar to the  last historically viewed locations in functionality.

**Comment by neilswann80** [comment]
For the moment I've been using this shell script to launch Taranis:

`#!/bin/sh

json=/mnt/ext1/system/state
config=/mnt/ext1/system/config
taranis=/mnt/ext1/applications/taranis

if [ -e $json/taranis.json ]; then
	cp $json/taranis.json $json/taranis.json.old
fi
if [ -e $config/taranis.cfg ]; then
	cp $config/taranis.cfg $config/taranis.cfg.old
fi

$taranis

if [ -e $json/taranis.json.old ]; then
	mv $json/taranis.json.old $json/taranis.json
fi
if [ -e $config/taranis.cfg.old ]; then
	mv $config/taranis.cfg.old $config/taranis.cfg
fi

exit`

**Comment by orontee** [comment]
Maybe` 5 items in history is just not enough? Or simply add a configuration key to disable updates of the `taranis.json` file?
@neilswann80 Let me think of it...

**Comment by neilswann80** [comment]
I was thinking along the lines of having some locations that do not get automatically overwritten as you view the weather in different locations.

As regards adding a favourite to the list, have either an on-screen button, or menu button that adds the currently viewed location as the favourite.  Perhaps that button could act as toggle to add/remove a favourite, with the icon changing depending on favorite status?

As regards removing a favourite, perhaps keep it simple and use the same mechanism as for the history; have a max number of favourites and oldest added is overwritten.

**Comment by orontee** [comment]
Maybe a checable button with star icon left to the location name? Would a single favorite be ok? I'd better keep the UI simple...

**Comment by neilswann80** [comment]
I travel around a bit, but have a few locations I visit regularly, so having 3-5 favourites would be ideal.  My launcher workaround is adequate for my needs though, but thinking there must be many other ebook reading commuters.  :)

To keep the UI simple perhaps just tuck the option away in the menu?  Or are you concerned about an overly cluttered menu also?  Perhaps have a simple (default) and advanced menu view?

I'm just creating work for you at this point!  :)  The app is great as it is though, just throwing ideas your way in case you like them.

**Comment by neilswann80** [comment]
Excuse the random  question...

I'm calling two functions one directly after the other.  The first makes a change to the display, the second calls the on-screen keyboard.  But the display change only occurs after I close the on-screen keyboard despite the display change function being called first,  Any idea why this might happen?

**Comment by orontee** [comment]
> Excuse the random question...
> 
> I'm calling two functions one directly after the other. The first makes a change to the display, the second calls the on-screen keyboard. But the display change only occurs after I close the on-screen keyboard despite the display change function being called first, Any idea why this might happen?

Does the "change to the display" includes a screen update (`FullUpdate()` for example)?

**Comment by neilswann80** [comment]
Weirdly if I call FullUpdate() after the display change change that also happens first!

Managed to solve it by setting the display changes, ClearScreen(), then redrawing, then call the keyboard.

Working with inkview functions is a little frustrating.  🙄

**Comment by orontee** [comment]
Maybe make sure the event queue is empty before the keyboard is open...

Matthias

**Comment by orontee** [comment]
Plan: Items in location history will be extended with a `favorite` boolean attribute and a star-shaped button added on the left of the location on main screen to toggle that value, and finally those locations with that attribute equal to `true` will never be popped from the history. A star icon can be set on menu items for favorite locations.

**Comment by orontee** [comment]
![new_location_menu](https://github.com/orontee/taranis/assets/2065954/16c5c87b-86a4-485f-a5ae-7c7fb2605f16)

**Comment by orontee** [comment]
@neilswann80 I'd be nice to have your feedback on this feature.

https://github.com/orontee/taranis/releases/tag/v1.2.0-rc2

**Comment by neilswann80** [comment]
Apologies for the late reply, I've been hiking in Portugal for a week.

Tested and the favourites feature works nicely, great work.  👍
