### ISSUE TITLE
Switch from One Call API to APIs covered by the Open-source plan

### ISSUE THREAD

**Issue by orontee** [orontee/taranis#44]
# Problem

The Open-source plan from Openweather does not increase the limits of One Call 3.0 API. This plan increases the API limits of Current Weather API and  3-hour forecast 5 days API.

The free limit for One Call 3.0 API is 1,000 calls per day.  With Open-source plan it increases to 3,000 calls per _minute_!

On September 16, 2023 there was a total of 281call to One Call 3.0 API coming from `taranis`. 

If the application spreads, we'll reach the the free limit. There are two options:
- We ask users to subscribe to Openweather and generate their own API key, but still distribute the application with an API key rate limited to 1,000 calls per day to stay below the limit where one has to pay
- We switch from One Call API to APIs covered by the Open-source plan.

See:
- https://openweathermap.org/price#current
- #5 

# Impact of the switch

* The hourly forecast becomes a 3-hour forecast
* The Open-source plan doesn't cover any API providing "daily forecasts", thus there's two options again:
  * Remove the daily forecast view
  * The daily forecast will be limited to 5 days and the underlying data must be computed by averaging 3-hour forecast data
* Alerts aren't available through the APIs covered by the Open-source plan

If we do the switch, when users provide their own API key, they should be allowed to choose to consume One Call API and benefit from alerts, hourly forecast and a daily forecast covering the full week.

# Comparison of both options

The first option is easy to implement: A warning in the [README.md](https://github.com/orontee/taranis/blob/main/README.md) file and, since the API returns a dedicated HTTP code, when the limit is reached, just display a message to ask users to generate their own API key or be patient when that code is received...

But standard users can't be asked to generate an API key and copy it in a configuration file...

With option two, one must average forecast which is not an easy task at all: What is the meaning of averaging weather descriptions??

# Conclusion

Which option should be implemented?

**Comment by neilswann80** [comment]
I prefer the option for generating a user specific API key.  There must be a way we can automate this to be it a tad simpler for the average user?

**Comment by orontee** [comment]
> I prefer the option for generating a user specific API key. 

Yes, this is the right thing to do. And its less work :smile: !

> There must be a way we can automate this to be it a tad simpler for the average user?

No, one has to register with valid email address before any API key can be generated.

Today I send an email to Openweather support to clarify the limitations of Open-source plan.

**Comment by orontee** [comment]
The application now reads the `api_key` key from configuration file. It allows anyone to use its own key.

Let live with this for now.
