### ISSUE TITLE
Location names in multiple countries

### ISSUE THREAD

**Issue by neilswann80** [orontee/taranis#56]
Less common scenario to consider...

Birmingham for example exists in the UK and the US.  If you search simply for "Birmingham" without specifying the country, a weather report is generated but it's not immediately clear for which country.

Could the location name written to the screen be extracted from the OpenWeather data payload (with country included) rather than writing the user input to the screen, so the exact location/country is clear?

**Comment by orontee** [comment]
# Two options

- Quick fix: Complete user input with the country information of the first location returned by the Geocoding API (the location used to request weather conditions)
- Offer user a choice of locations built from the locations returned by the Geocoding API when there's not a unique location

# Complement
```
$ curl "https://api.openweathermap.org/geo/1.0/direct?q=Saint%20Malo,France&lang=fr&appid=${OWM_API_KEY}"
[{"name":"Saint-Malo","local_names":{"ko":"생말로","br":"Sant-Maloù","fr":"Saint-Malo"},"lat":48.649518,"lon":-2.0260409,"country":"FR","state":"Brittany"}]
```
Remarks:
* Note that the country is a code, not the full name. I guess it's ok to display that name and not the exact user input.
* One could choose the local name corresponding to current language

**Comment by neilswann80** [comment]
Excellent start!

> * Note that the country is a code, not the full name. I guess it's ok to display that code and not the exact user input.

I fit's just the two-letter `ISO-3166-1 ALPHA-2` country codes it would be easy enough to use an alias file to write the full country name.  See text file.

[data_csv.txt](https://github.com/orontee/taranis/files/12830697/data_csv.txt)

**Comment by neilswann80** [comment]
This looks like a useful resource:
https://github.com/umpirsky/country-list

**Comment by orontee** [comment]
Work is ongoing on this topic but unfortunately don't expect to much from Geocoding API...

```sh
$ curl "https://api.openweathermap.org/geo/1.0/direct?q=Saint,France&lang=fr&appid=${OWM_API_KEY}"
[{"name":"Saint","local_names":{"hi":"सैंत"},"lat":27.370281,"lon":77.3582553,"country":"IN","state":"Rajasthan"}]
```

I am not even able to find a query with multiple answers...

**Comment by orontee** [comment]
Current implementation doesn't try to display local names, nor transform country codes into full country names.

Let see whether we need those refinements; It's not clear to me.

**Comment by neilswann80** [comment]
Works nicely here. Surprising how many location names appear in other parts of the world!  😃 

Just having the country code is likely sufficient, no?  Most people are used to seeing this from webforms and the like.

Couldn't hurt to have the longitude and latitude in the location list.

**Comment by orontee** [comment]
> Works nicely here. 

Thanks for the feedback!

> Surprising how many location names appear in other parts of the world! 😃

Yes. I am not sure the Geocoding API is that precise and of good quality...
 
> Just having the country code is likely sufficient, no? Most people are used to seeing this from webforms and the like.

Right.
 
> Couldn't hurt to have the longitude and latitude in the location list.

Yes, I'll make list items spread over two lines, the second being dedicated to longitude and latitude.

**Comment by orontee** [comment]
![screenshot](https://github.com/orontee/taranis/assets/2065954/fb2397c7-1436-4c54-8f7c-3213ca0efd9f)

**Comment by orontee** [comment]
Yes, the user experience has improved a lot!

I'll will release this soon. Other awaiting issues are stucked and I suspect they won't progress in a short delay.

**Comment by neilswann80** [comment]
Just wanted to check... taranis.cfg is no longer created.  Does Tarnis now use the first entry in the .json file as the location to load on app launch?

**Comment by orontee** [comment]
You're right. Most recent item in history is used (Toulouse if history is
empty).

The config file should be created after a change of unit for example.

Matthias

**Comment by neilswann80** [comment]
Or if you change view to 8-day I presume?

**Comment by orontee** [comment]
Yes. But this should change in the future because it's more related to the
application state than a configuration...

Matthias
