### ISSUE TITLE
Forecast displayed at startup should be configurable

### ISSUE THREAD

**Issue by orontee** [orontee/taranis#59]
# Context

The `display_daily_forecast` key of configuration file is currently used to store the application state.

This is wrong and makes the configuration file change whenever the user browse the different forecasts!

# Todo

Introduce a new configuration key `start_with_daily_forecast` with boolean value. When equal to `true`, the application will show the daily forecast at startup. The default is to show the hourly forecast.

**Comment by neilswann80** [comment]
Despite adding `start_with_daily_forecast = true` it's launching with the hourly forecast for me every time.

**Comment by orontee** [comment]
@neilswann80 Please, can you try this syntax `start_with_daily_forecast=true` (without spaces around the equal sign) and remove the `taranis.cfg.back` file if any?

**Comment by neilswann80** [comment]
Yep... of course that fixed it.  I am an idiot!

Many thanks.

**Comment by orontee** [comment]
> Yep... of course that fixed it. I am an idiot!

No! The format of those `.cfg` files is not documented and unpredictable!

I fixed the [README.md](./README.md) file.
