### ISSUE TITLE
Weather alert content can overfill the message box

### ISSUE THREAD

**Issue by neilswann80** [orontee/taranis#66]
I noticed a recent weather alert contained so much content it overfilled the message box so you are unable to see/read the beginning of the message.  

As there is no option to scroll within a message, perhaps break the content into multiple pages based on a max number of lines?

**Comment by orontee** [comment]
> I noticed a recent weather alert contained so much content it overfilled the message box so you are unable to see/read the beginning of the message.
> 
> As there is no option to scroll within a message, perhaps break the content into multiple pages based on a max number of lines?

Alerts are currently shown through a call to the `Dialog()` function, https://github.com/orontee/taranis/blob/main/src/alerts.cc#L67. AFAICT this function doesn't support vertical scrolling.

The easiest solution is to elide the alert description after a fixed number of characters. Ugly. But other solutions look quite complicated to my eyes.

**Comment by orontee** [comment]
@neilswann80 Hey what was the location of that alert???

I just copy-pasted the lyrics of the song I was listening to in the first alert of my `taranis.json` file and with more or less 400 characters it looks ok!

![screenshot](https://github.com/orontee/taranis/assets/2065954/a58c2b52-dd6b-4244-9a40-418339c79c8d)

**Comment by neilswann80** [comment]
Today's weather alert on `Bristol, GB` is an example of the overfill.

**Comment by orontee** [comment]
I'll investigate how to use what `scrollview.h` in the SDK has to offer...

**Comment by orontee** [comment]
First step: Implement an alert viewer.
![screenshot](https://github.com/orontee/taranis/assets/2065954/7bc29a4d-997a-4185-8c94-0f9dc834c525)

**Comment by orontee** [comment]
Implemented using `AddScrolledArea/RemoveScrolledArea` and consuming `EVT_SCROLL`. Not very smooth and missing a scroll bar but good enough for such a marginal case where the alert description would fill the entire screen...
