### ISSUE TITLE
Option to check whether a new version is available

### ISSUE THREAD

**Issue by orontee** [orontee/taranis#79]
# Proposal

1. Remove menu item to open about dialog
2. Add a "Software" sub-menu in "Parameters" view
3. Three items:
- "Software version", action that pops up the about dialog (with current version)
- "Software update", action that checks whether a new version is available, pops up a dialog to notify user and offers choice to download last version if different from current  version and move file to current executable file
- "Auto Update", on/off choice to periodically perform the previous action

## Remarks
* Removing the about dialog item menu make the menu shorter!
* The "Auto update" periodicity could be once a week; A timestamp for last check should be serialized in application state
* First implementation may stop after the version check, since I don't know whether it's possible to find current executable path, or extract from a zip archive, nor (main concern) it is acceptable from user point of view to have the application install things from the Internet.
* Complement: Install is acceptable iff a signature check is implemented; Challenging but interesting! Openssl is installed so seems reasonable.

**Comment by orontee** [comment]
Work is ongoing and a MVP is already working with manual version check.

Still have to save last check timestamp in model and application state, and automatize the check.

But working on this I feel that all that stuff is irrelevant to a weather application and should move to a 3rd party application with version check, signature check, unzip and install... In two words, an application store!

**Comment by orontee** [comment]
Users interested in pre-relesaes can set `version_check_keep_pre_releases` to `1` in `taranis.cfg` file.

**Comment by orontee** [comment]
The "check for new version" is implemented. Let's take some time to think of the "download, verify and update software" part.

**Comment by neilswann80** [comment]
This app has a download mechanism: http://komary.net/pbdownload/

**Comment by orontee** [comment]
> This app has a download mechanism: http://komary.net/pbdownload/

Thank you, @neilswann80. Nice example of the use of the SDK functions to perform and track downloads. It's definitively the path to follow: Provide an application dedicated to version check, download, verify and install.

Unfortunately, it:
- Manage a single application only
- Lacks "unzipping" 
- Lacks the verification step

The third step is difficult and require playing with OpenSSL or GnuPG.

**Comment by orontee** [comment]
Interesting investigations on the ".pbi" format: https://www.mobileread.com/forums/showpost.php?p=4385836&postcount=1

**Comment by neilswann80** [comment]
FYI I use the following update script to update my version of Taranis when a new version becomes available,

`#!/bin/sh
mkdir /var/tmp/taranis
wget https://github.com/orontee/taranis/releases/latest/download/taranis.zip -O /var/tmp/taranis/taranis.zip
unzip /var/tmp/taranis/taranis.zip -d /var/tmp/taranis
cp -f /var/tmp/taranis/taranis.app /mnt/ext1/applications/taranis.app
rm -rf /var/tmp/taranis`

Could this be streamlined into Taranis?

**Comment by orontee** [comment]
Do you reboot after that? My experience is that there's a kind of cache and replacing the executable then restarting through an icon click isn't enough to start the new executable...

Side remark. Reading your commment, I realized that the '.app' file could be attached to the release. Unzipping would then be unnecessary. Missing '.app' file from the release would tell that a manual install is required. Interesting.  But I'd still prefer to download the '.pbi' to be able to perform a full install.

Then back to my rengaine: This is the work of a dedicated application, not Taranis.

Since I made no progress on the gargoyle port, I am worrying whether I should work on that application...

Last remark, I've found that downloading the installer manually, copying to the device, etc. is so boring... I even didn't installed last minor release on my device. Improvment required!

**Comment by neilswann80** [comment]
I don't need to reboot.  I don't run the script with Taranis open, if that is what is causing your issue?  Although a killall commad could be added to close Taranis and then relaunch it after the update.

**Comment by orontee** [comment]
No I don't think my problem comes from the application being running. I guess it comes from the application having run before in the same boot. 

I must do some tests.

**Comment by neilswann80** [comment]
> No I don't think my problem comes from the application being running. I guess it comes from the application having run before in the same boot.
> 
I launched the old version of Tananis, ran my script, launched the new version of Taranis all within the same 
session, no reboot required.  I checked the version number within the app before and after, so no cached issue on my device.
