### ISSUE TITLE
Add temperature units sign next to degrees

### ISSUE THREAD

**Issue by kakonema** [orontee/taranis#91]
<img src="https://github.com/orontee/taranis/assets/6775445/f6a9ac4a-2b34-46a0-bd6c-d385c3d88cd4" width=300/>

Hello, I'm not sure what to make of the temp it shows, so it would be nice to have units next to degrees sign (C, F or K). 
It's from Pocketbook Era (7'' device with 1264x1680 res, 300 ppi).

**Comment by orontee** [comment]
Thanks for reporting @kakonema !

Is this what you're interested in?
<img src="https://github.com/orontee/taranis/assets/2065954/087a8dbf-4382-4e66-95b9-483d47c88090"  width="300" height="auto"/>

**Comment by orontee** [comment]
It'll be included in next release.

**Comment by kakonema** [comment]
Yes, this is exactly what i was looking for, thanks!
