### ISSUE TITLE
Apostrophes in Weather Alert info

### ISSUE THREAD

**Issue by neilswann80** [orontee/taranis#97]
Apostrophes in Weather Alert info cause an issue, displayig as: ***â€tm***

See example below:
<img src="https://github.com/user-attachments/assets/fd68f7a0-dc8a-4ead-96ea-7abf6247ede2" width=50%/>

**Comment by orontee** [comment]
Thank you for reporting!

Can you attach the `/mnt/ext1/system/state/taranis.json` file? It contains the application model serialized in JSON. It will help to reproduce and analyze the problem.

**Comment by neilswann80** [comment]
> Thank you for reporting!
> 
> Can you attach the `/mnt/ext1/system/state/taranis.json` file? It contains the application model serialized in JSON. It will help to reproduce and analyze the problem.

I'm not getting any weather alerts currently, so will the JSON still help?  I've had the screenshot saved for a while.

**Comment by orontee** [comment]
Tested with various Unicode characters in alert description (writing the characters directly in the `taranis.json` file) and it's ok; The following text was rendered as expected:

> It's an apostrophe, it’s a right single quotation mark, it‘s a left single quotation mark! À aussi en français accentuons le débat. 

One can thus expect that the content of the state file is wrongly encoded when the problem happens. Can come from a wrong deserialization of the OpenWeather API response or a wrong encoding while writing the state file.

**Comment by orontee** [comment]
I failed to reproduce up to now. Please post the location and `taranis.json` file if the problem appears once again.

**Comment by neilswann80** [comment]
It's happening for today's weather alert for Bistol-UK.

[taranis.json](https://github.com/user-attachments/files/17867366/taranis.json)

Also the last line of the alert is partly cut-off:
![taranis](https://github.com/user-attachments/assets/f467390e-482a-4d57-91f1-a20ffb7175b5)

**Comment by orontee** [comment]
From the logs I read the URL requested.

Then I checked that the response headers says that the encoding used is UTF-8 but the payload is wrongly encoded since terminal support UTF-8:
```
matthias@peitho:~ $ curl --verbose --output payload_with_wrong_accents.json "https://api.openweathermap.org/data/3.0/onecall?lon=-2.5973&lat=51.453802199999998&units=metric&exclude=minutely&lang=fr&appid=4620ad6f20069b66bc36b1e88ceb4541" 2>&1 | grep -E charset
< Content-Type: application/json; charset=utf-8
matthias@peitho:~ $ cat payload_with_wrong_accents.json | grep --only-matching -E "It.*easy"
Itâ€™s easy
matthias@peitho:~ $ echo -e '\xe2\x82\xac'   # Print euro sign to check terminal supports UTF-8 encoding
€
```

And finally, on OpenWeather website itself:

![image](https://github.com/user-attachments/assets/44db5083-83df-466a-9a73-3cbfed423acb)

Conclusion: Not a Taranis bug!

**Comment by neilswann80** [comment]
Although not a Taranis issue then, would it be worth adding a workaround to substitute "â€tm" for an apostrophe anyway?

And what about the last line of the alert being cut off?  Does that need raising as a separate issue?

Thanks.
